#!/bin/sh
#
# gen_kallsyms_extra.sh - regenerate kallsyms_extra.h from the XNU source.
#
# /proc/kallsyms lists non-exported kernel symbols too, but macOS ships the arm64
# kernel stripped of local symbols (only ~6894 exported symbols survive in the
# image). We recover the NAMES of the non-exported symbols straight from the XNU
# source with ctags; they have no address in the running kernel, so the daemon
# emits them with address 0 (which is also what kptr_restrict shows non-root for
# every symbol). This script produces an embeddable C array of those names.
#
# Requires Exuberant/Universal ctags. The XNU source is the lib/xnu submodule by
# default (override with XNU_SRC); the result (kallsyms_extra.h) is committed so
# builds work without the submodule checked out or ctags installed.
#
#   git submodule update --init lib/xnu
#   tools/gen_kallsyms_extra.sh
#
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
XNU_SRC="${XNU_SRC:-$SCRIPT_DIR/../lib/xnu}"
OUT="${1:-$SCRIPT_DIR/kallsyms_extra.h}"

if ! command -v ctags >/dev/null 2>&1; then
    echo "gen_kallsyms_extra: ctags not found; keeping existing $OUT" >&2
    exit 0
fi
if [ ! -d "$XNU_SRC" ]; then
    echo "gen_kallsyms_extra: XNU source '$XNU_SRC' not found; keeping $OUT" >&2
    exit 0
fi

names="$(mktemp)"
runtime="$(mktemp)"
trap 'rm -f "$names" "$runtime"' EXIT

# Function and variable definitions from the kernel source.
ctags -x --c-kinds=fv -R \
    "$XNU_SRC/bsd" "$XNU_SRC/osfmk" "$XNU_SRC/iokit" \
    "$XNU_SRC/libkern" "$XNU_SRC/pexpert" "$XNU_SRC/security" 2>/dev/null \
    | awk '{print $1}' \
    | grep -E '^[A-Za-z_][A-Za-z0-9_]*$' \
    | grep -vxE 'if|for|while|switch|return|sizeof|else|do|case|default|goto|break|continue|typedef|struct|union|enum|static|const|volatile|inline|void|int|char|long|short|unsigned|signed|float|double|register|extern' \
    | sort -u > "$names"

# Drop names already present in the running kernel image (those are exported and
# emitted with their real address by the daemon); keep only the non-exported set.
kver="$(sysctl -n kern.version 2>/dev/null || true)"
soc="$(printf '%s' "$kver" | sed -n 's/.*ARM64_\([A-Za-z0-9]*\).*/\1/p' | tr 'A-Z' 'a-z')"
kimg="/System/Library/Kernels/kernel.release.${soc}"
[ -f "$kimg" ] || kimg="/System/Library/Kernels/kernel"
if command -v nm >/dev/null 2>&1 && [ -f "$kimg" ]; then
    nm "$kimg" 2>/dev/null | awk '{print $3}' | sed 's/^_//' | sort -u > "$runtime"
    comm -23 "$names" "$runtime" > "$names.f" && mv "$names.f" "$names"
fi

count="$(wc -l < "$names" | tr -d ' ')"
{
    echo "/*"
    echo " * kallsyms_extra.h - generated by gen_kallsyms_extra.sh; do not edit."
    echo " *"
    echo " * Non-exported XNU kernel symbol names recovered from the source tree."
    echo " * The arm64 kernel image is stripped of these, so /proc/kallsyms emits"
    echo " * them with address 0. Regenerate with tools/gen_kallsyms_extra.sh."
    echo " */"
    echo "static const char *const procfs_kallsyms_extra[] = {"
    sed 's/.*/    "&",/' "$names"
    echo "};"
    echo "static const unsigned procfs_kallsyms_extra_count ="
    echo "    (unsigned)(sizeof(procfs_kallsyms_extra) / sizeof(procfs_kallsyms_extra[0]));"
} > "$OUT"

echo "gen_kallsyms_extra: wrote $count names to $OUT" >&2
